-- 创建用户提示词选择表
CREATE TABLE IF NOT EXISTS user_prompt_selections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  prompt_id BIGINT NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, prompt_id)
);

-- 创建RLS策略
ALTER TABLE user_prompt_selections ENABLE ROW LEVEL SECURITY;

-- 创建用户提示词选择表的RLS策略
-- 1. 用户只能查看自己的提示词选择
CREATE POLICY "用户可以查看自己的提示词选择" ON user_prompt_selections
  FOR SELECT USING (auth.uid() = user_id);

-- 2. 用户只能插入自己的提示词选择
CREATE POLICY "用户可以插入自己的提示词选择" ON user_prompt_selections
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 3. 用户只能删除自己的提示词选择
CREATE POLICY "用户可以删除自己的提示词选择" ON user_prompt_selections
  FOR DELETE USING (auth.uid() = user_id);

-- 注释
COMMENT ON TABLE user_prompt_selections IS '存储用户选择的提示词';
COMMENT ON COLUMN user_prompt_selections.id IS '选择ID';
COMMENT ON COLUMN user_prompt_selections.user_id IS '用户ID';
COMMENT ON COLUMN user_prompt_selections.prompt_id IS '提示词ID';
COMMENT ON COLUMN user_prompt_selections.created_at IS '创建时间';
